@startuml
'https://plantuml.com/sequence-diagram
loop while True:
ref over BinanceWebSocketApiSocket
send message
end
BinanceWebSocketApiSocket -> BinanceWebSocketApiConnection:receive()
BinanceWebSocketApiConnection-->BinanceWebSocketApiSocket : received_stream_data_json
BinanceWebSocketApiSocket->BinanceWebSocketApiManager:process_stream_data(received_stream_data)
BinanceWebSocketApiManager->BinanceWebSocketApiManager.stream_buffer:append(stream)
end
'데이터 프로세싱은 BinanceStreamManager에서 처리

BinanceStreamManager -> BinanceWebSocketApiManager:pop_stream_data_from_stream_buffer()
activate BinanceWebSocketApiManager
BinanceWebSocketApiManager -> BinanceWebSocketApiManager.stream_buffer:pop(0)
BinanceWebSocketApiManager.stream_buffer --> BinanceWebSocketApiManager:stream
BinanceWebSocketApiManager-->BinanceStreamManager : stream
deactivate BinanceWebSocketApiManager

@enduml
